influxdb:
    image: tutum/influxdb:0.9
    env_file: .env
    ports:
        - "8083:8083"
        - "8086:8086"
    volumes:
        - ./config/influxdb.toml:/config/config.toml:ro
    restart: on-failure:99
mysql:
    image: tutum/mysql:5.6
    env_file: .env
    ports:
        - "3306:3306"
    volumes:
        - ./tools/database.sql:/database.sql:ro
    restart: on-failure:99
concava:
    build: .
    env_file: .env
    ports:
        - "3000:3000"
    volumes:
        - ./config/concava.js:/data/config.js:ro
    links:
        - influxdb
        - mysql
    restart: on-failure:99
